(Optional) fix for .debug_line head generation
pret/agbcc pull request #51
Opened 2022-03-02 19:37 UTC by StanHash

Sometimes when using tools for reading line number information out of objects generated by agbcc, you'd get the follwing error:

    DWARF error: mangled line number section

This is presumably caused by the function `size_of_line_info` (in gcc/dwarf2out.c) sometimes mispredicting the actual size of the rest of the `.debug_line` section. This was fixed here by generating label deltas instead of using that function (as is done in more recent versions of GCC).

An optional `-flegacy-debug-line-info` flag is provided to restore the old (buggy) behavior in the rare case where generating matching debug information is desired.

Note: that fix probably needs to eventually be ported to agbcc_arm as well as any fork featuring agbcp.

---

I'm only now seeing that there's another debug info related PR in (#49) featuring the addition of a new flag. Perhaps it would be interesting to merge the flags into an unified one that either updates/fixes debug info generation or restores the old buggy one.

2022-03-03 11:06 UTC, laqieer commented
https://github.com/gcc-mirror/gcc/commit/14a774a9d22db91fb6387cb8eb61060b61782f29
reference for code review

2023-04-04 07:37 UTC, StanHash commented
Updated this to not enable new fixed behavior by default.

2023-04-05 03:27 UTC, luckytyphlosion requested changes

2023-04-05 03:27 UTC, luckytyphlosion commented on gcc/toplev.c
> +int flag_fixed_debug_line_info = 0;
Fix comment

2023-04-05 14:05 UTC, merged